### ISSUE TITLE
Linter config

### ISSUE THREAD

**Issue by ravish-garg** [iljapostnovs/ui5plugin-linter#112]
Can the linter config be in a file of its own like .eslintrc etc., instead of polluting the package.json?

**Comment by iljapostnovs** [comment]
Hi.

Not yet :)
I was just thinking about adding support for .rc files, now I have a request for that ;)
I will introduce it probably in next 7 days.

**Comment by iljapostnovs** [comment]
Done.

Please test it and let me know if it works for you :)

**Comment by ravish-garg** [comment]
Perfect solution, didn't expect it to be so quick. And thank you for such an awesome extension.
