### ISSUE TITLE
TagLinter: class doesn't exist /  aggregation doesn't exist

### ISSUE THREAD

**Issue by racflx** [iljapostnovs/ui5plugin-linter#121]
**Describe the bug**
Bug appears in VSCode extension.

TagLinter reports "class doesn't exist" when custom controls from a third-party library are added to XML views.
TagLinter reports "aggregation doesn't exist" when custom controls are added to XML views.

Also, the attributes are marked as invalid.

**To Reproduce**
1. Create a custom control
2. Include the custom control in the XML view

**Expected behavior**
The control, whether third party or own, should be recognized by the linter.

**Additional context**
The custom controls are written in TypeScript. The third-party custom controls in JavaScript.
In addition, the custom controls can be accessed in controllers without any problems and there are no other error messages either.

**Comment by iljapostnovs** [comment]
Hi,

Thanks for bug report.
Please provide minimal project example in order to reproduce the issue.

**Comment by racflx** [comment]
Structure:

```
├── frontend
|   ├── src
|   |   ├── components
|   |   |  ├── custom
|   |   |     ├── customControl1.ts
|   |   |     └── customControl2.ts
```

The custom controls are implemented in a single file with the following structure:

```typescript
// Module

declare module "./customControl1" {
  interface $CustomControl1Settings extends $ControlSettings {
      //
  }

  export default interface ICustomControl1 {
      //
  }
}

// Class

/**
* @namespace project.frontend.custom
*/
export default class CustomControl1 extends Control {
  // control implementation
}
```

&rArr; **Usage in XML view:**
```xml
<mvc:View
	controllerName="project.frontend.controller.test"
	xmlns="sap.m"
	xmlns:custom="project.frontend.custom"
>
  <Page>
    <VBox>
      <!--Taglinter: "CustomControl1" aggregation doesn't exist in "sap.m.VBox"-->
      <custom:CustomControl1 />
    </VBox>
  </Page>
</mvc:View>
```

As mentioned above, the controls are rendered and no other errors occur when they are used.
I hope this example is helpful.

**Comment by racflx** [comment]
I found the problem: 

The file name of the custom control was written in Kebap case, changing the file name back to Pascal case, like the class name, solved the problem.

**Comment by iljapostnovs** [comment]
> I found the problem:
> 
> The file name of the custom control was written in Kebap case, changing the file name back to Pascal case, like the class name, solved the problem.
Good. Keep the PascalCase, it's the same way as SAP uses for their classes :)
Are there any other problems? If no, this issue might be closed.
