### ISSUE TITLE
Feature Request: Default values linter

### ISSUE THREAD

**Issue by mateusz-matyjaszczyk** [iljapostnovs/ui5plugin-linter#122]
I would like to ask to add a configuration that would allow to disable "information" about unnecessary value because it is the same as default. 
Let's take a table for example:
![CleanShot 2023-06-30 at 03 59 14](https://github.com/iljapostnovs/ui5plugin-linter/assets/26802754/302f9565-74d5-4cfe-a817-cafa31d7085e)
![CleanShot 2023-06-30 at 03 59 21](https://github.com/iljapostnovs/ui5plugin-linter/assets/26802754/8a67ebd3-7e79-45aa-a67c-96f123d498cd)

If there is already a parameter that would allow to disable this hint it would be great but I couldn't find it... This is especially helpful with forms but can be used in many other scenarios when you want to set the value so everyone know point-blank what it is - without checking the documentation for default value but in the same time don't want to have that blue line about unnecessary assignment.

**Comment by iljapostnovs** [comment]
Sure. I will add it in the next release.

Meanwhile you can put `ui5ignore` with specific attribute
![image](https://github.com/iljapostnovs/ui5plugin-linter/assets/31005247/470f0919-0a94-49bb-a97d-2a19d2b1ca1a)

**Comment by iljapostnovs** [comment]
Done in v1.8.0.

VSCode Extension will be updated a bit later.

**Comment by iljapostnovs** [comment]
VSCode Extension updated. Please check.
