### ISSUE TITLE
Feature request: Support formatting from SAPUI5 Extension via npm script

### ISSUE THREAD

**Issue by MichaelFlucher** [iljapostnovs/ui5plugin-linter#130]
**Describe the feature**
In order to have a consistent formatting I'm using eslint and prettier to format the code. For XML files, the prettier/xml formatter is not the best in regards to UI5. I'm not sure if there is already a possibilty to format the XML files, but for now, `npx ui5linter` only shows the errors. Would be nice to have something like `npx ui5linter --format  *.xml`.

**Comment by iljapostnovs** [comment]
Hi @MichaelFlucher
Apologies for the delay.

XML moved to linter repo:
[Readme](https://github.com/iljapostnovs/ui5plugin-linter?tab=readme-ov-file#xml-formatter)

Please check if it works for you

**Comment by MichaelFlucher** [comment]
Works pretty good, thank you 👍🏽
