### ISSUE TITLE
Feature request: Indentation setting for the XMLFormatter

### ISSUE THREAD

**Issue by netux** [iljapostnovs/ui5plugin-linter#138]
**Describe the feature**
Add a way to configure the indentation used to reconstruct XML files after formatting. Currently, the formatter forces tabs.

If possible, it'd also be nice to have an option to auto-detect and preserve the indentation of a file (maybe by default?).

**Screenshots**
N/A

**Additional context**
The project I'm working on uses 4 spaces for indentation (not really my choice), and I'd like for xml files to be consistent with that setting as well.

**Comment by netux** [comment]
Other ideas to expand on this:
- Read indentation setting from editorconfig, eslint, or prettier config files; or via VSCode directly when using the extension.
- Add a linter rule to detect mixed indentation.

**Comment by iljapostnovs** [comment]
I've added indentation determination from vscode preferences. 
If "insert spaces" is set to true, spaces are added. Space quantity depends on "tabSize" 
![image](https://github.com/iljapostnovs/ui5plugin-linter/assets/31005247/d6393101-4fd1-4374-b8d0-ca9ba4da7ed2)

In the rest of the cases, tab is used as indentation.
Please check

**Comment by netux** [comment]
Works pretty well through VSCode. Thanks!

I have left a small comment on #139, but the main purpose of this ticket was done, so i will close it.
