### ISSUE TITLE
Bug: Changes to ui5 linter configuration do not affect linter behaviour

### ISSUE THREAD

**Issue by skorolev-tjc** [iljapostnovs/ui5plugin-linter#148]
**Describe the bug**
Tried to switch off some of the ui5 linter parameters in ui5 -> ui5linter -> usage, for example WrongParametersLinter, PublicMemberLinter.
Tried to use different configuration files: package.json, .ui5pluginrc.json. Tried reloading window, disabling/enabling the ui5 extension, and quitting VSCode.

These changes do not affect the behaviour of the plugin whatsoever.  
In any case the linter continues to report the issues

**To Reproduce**

1. Add parameter WrongParametersLinter to the usage section with "false" value
2. Reload VSCode window
3. Check the editor and Problems that they still report the issue

**Expected behavior**
If I turn off the linter feature via usage I expect that it stops reporting the respective issue.

**Screenshots**

package.json configuration:
<img width="434" alt="image" src="https://github.com/iljapostnovs/ui5plugin-linter/assets/42373743/2c2635dd-0b89-4b28-843c-ff6faecd3ec4">

Nevertheless the editor show the issue:
<img width="1567" alt="image" src="https://github.com/iljapostnovs/ui5plugin-linter/assets/42373743/675c32f1-25ac-4669-8378-c49b1c3b1d27">

Also issues are reported in the Problems tab:
<img width="1302" alt="image" src="https://github.com/iljapostnovs/ui5plugin-linter/assets/42373743/7f17339a-d0ba-43a0-931b-8f3daa1f598c">

**Desktop (please complete the following information):**

-   OS: macOS Sonoma 14.4
- Extension version: 
<img width="727" alt="image" src="https://github.com/iljapostnovs/ui5plugin-linter/assets/42373743/f0321666-f7ac-43d0-af34-5903db38c3f5">

**Additional context**
I use ui5 -> ui5parser -> proxyWorkspaces configuration parameter due to the project specifics.

**Comment by iljapostnovs** [comment]
Hi!
I see that you are using `proxyWorkspaces`, which might be the reason why your config in the same `package.json` is not working.
Please try to configure the extension in `./ui/package.json`. 
[Readme](https://github.com/iljapostnovs/ui5plugin-parser/blob/master/README.md#proxy-workspaces)

**Comment by skorolev-tjc** [comment]
Hi
Yes, thanks, it works if I move the config to ui/package.json and remove proxyProjects


Best regards,

[https://storage.letsignit.com/61643f9b492936fddb726a94/generated/effects_4b30e6c823b3c7b85688ef3b1c52d869664779a9170d0853240f26d3.png]<https://cloud.letsignit.com/collect/bc/61653b7922c19c167c77729b?p=QWtJhe58Mtc39y5QfyP92cbAcJ_Pg_yyoW0UhNt08vaiOlW6Za1HDZJkHaszpcEFcOTXFLf_osZ2I84cua9wPOU_z5ON46A5aOWtw6zRNVzW9tucqnXzsbqZvhQMl52p7rrTpa9IoaJHZjPBOMNhHhMbNPVf42KzYJzsVVKALMU=>

Sergey Korolev

Senior Software Engineer

+44 7776 687650

***@***.******@***.***>



From: Ilja Postnovs ***@***.***>
Date: Thursday, 28 March 2024 at 5:12 PM
To: iljapostnovs/ui5plugin-linter ***@***.***>
Cc: Sergey Korolev ***@***.***>, Author ***@***.***>
Subject: Re: [iljapostnovs/ui5plugin-linter] Bug: Changes to ui5 linter configuration do not affect linter behaviour (Issue #148)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi!
I see that you are using proxyWorkspaces, which might be the reason why your config in the same package.json is not working.
Please try to configure the extension in ./ui/package.json.
Readme<https://github.com/iljapostnovs/ui5plugin-parser/blob/master/README.md#proxy-workspaces>
