### ISSUE TITLE
Wrong TagAttribute/TagLinter Error in XML Fragment

### ISSUE THREAD

**Issue by MichaelFlucher** [iljapostnovs/ui5plugin-linter#38]
**Describe the bug**
I have a simple XML Fragment which includes the `sap.m.upload.UploadSet`:
```xml
<c:FragmentDefinition xmlns="sap.m" xmlns:c="sap.ui.core" xmlns:upload="sap.m.upload">
    <upload:UploadSet id="uploadCollection" instantUpload="false" />
</c:FragmentDefinition>
```

Using the `ui5linter` I get the following errors:
```
\view\fragments\step3Attachments.fragment.xml:2:45 Invalid attribute name (instantUpload) (TagAttributeLinter)
\view\fragments\step3Attachments.fragment.xml:2:5 "sap.m.upload.UploadSet" class doesn't exist (TagLinter)
```

**To Reproduce**
1. Include the fragment in a ui5 project
2. run either `npx ui5linter` or globally `ui5linter`

**Expected behavior**
I'm using `1.89.0` in Plugin Configuration and in ui5parser configuration. Also tried to add `sap.m.upload` as parser lib in `package.json`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 10

**Additional context**
npm v 6.14.15, node v v14.18.0, ui5linter v 0.5.7

**Project attachment**

**Comment by iljapostnovs** [comment]
Hi,

Interesting, I do not have such issues:
![image](https://user-images.githubusercontent.com/31005247/136939663-2e614f85-b368-4629-a618-46551d9dd6bc.png)

Could you try to delete node_modules/.cache folder and remove sap.m.upload from libs to load afterwards?

**Comment by iljapostnovs** [comment]
By the way, for clearing out such confusion with library version I have added UI5 version in the console log output of the linter.
