### ISSUE TITLE
Is it possible to disable the linter for a specific file?

### ISSUE THREAD

**Issue by jberthe** [iljapostnovs/ui5plugin-linter#64]
**Describe the bug**
In my OPA5 file, the structure is not the same as a controller, thus, the plugin doesn't work properly. 

Error :
No references found for "com.mycompany.app.**test.integration.AllJourneys**" classUnusedClassLinter(UI5Plugin)

**To Reproduce**
Create an integration test with files AllJourneyes.js

No references found for "com.mycompany.app..test.integration.AllJourneys" classUnusedClassLinter(UI5Plugin)

**Expected behavior**
Having like ESLINT the feature : /* eslint-disable */ such as /* ui5lint-disable */

**Comment by iljapostnovs** [comment]
Hi,

Extension is using https://www.npmjs.com/package/ui5plugin-linter for linting.
You can exclude classes from linting using package.json:
```json
 "jsClassExceptions": ["com.test.MyCustomClass1", "com.test.MyCustomClass2"]
```
Did you check the readme or it's doesn't fit your needs?

**Comment by jberthe** [comment]
Thanks a lot, I didn't know how it worked. But you highligth my thougths.
