### ISSUE TITLE
Invalid attribute name (displayBlock)TagAttributeLinter(UI5plugin)

### ISSUE THREAD

**Issue by jberthe** [iljapostnovs/ui5plugin-linter#68]
Hello, 

When I check a XML view I have all the time **Invalid attribute name ** whereas the attribute is correct.

To reproduce : Create a Freestyle application from the template, then open the xml file : 
![image](https://user-images.githubusercontent.com/6067155/173685177-78b5f851-fadc-4ab7-be8e-b88ac88d511d.png)
 
As configuration I use _ui5Version_ : 1.71.34 

Regards,
Joseph

**Comment by jberthe** [comment]
Hello,

I have changed the ui5version to 1.84.26 and the problem vanished. How can we found the rigth version ? 

Regards,
Joseph

**Comment by iljapostnovs** [comment]
Hi,

I've tried to put 1.71.34 and everything is working fine for me.
Please attach the project example, so I could debug it.

**Comment by iljapostnovs** [comment]
Closed because of inactivity
